apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-budget-frontend
  namespace: travel-budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-budget-frontend
  template:
    metadata:
      labels:
        app: travel-budget-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/jacoisrael2/travel-budget-frontend:latest
        ports:
        - containerPort: 80
